services:

  db: 
    image: postgres:15
    container_name: borealis-db
    restart: always
    environment:
      POSTGRES_USER: borealis
      POSTGRES_PASSWORD: borealis
      POSTGRES_DB: borealis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    image: api-borealis:latest
    container_name: borealis-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - runner

  auth-grpc:
    build: 
      context: .
      dockerfile: docker/auth/Dockerfile
    command: python -m auth.auth
    image: auth-borealis:latest
    container_name: borealis-auth-grpc
    ports:
      - "50053:50053"
    env_file:
      - .env
    depends_on:
      - db
      - runner

  auth-http:
    build: 
      context: .
      dockerfile: docker/auth/Dockerfile
    command: uvicorn auth.main:Borealis --host 0.0.0.0 --port 7000
    image: auth-borealis:latest
    container_name: borealis-auth-http
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - db
      - runner

  runner:
    build: 
      context: .
      dockerfile: docker/runner/Dockerfile
    image: runner-borealis:latest
    container_name: borealis-runner
    ports:
      - "50051:50051"
    env_file:
      - .env
    volumes:
      - /var/borealis/jobs:/var/borealis/jobs
      - /var/run/docker.sock:/var/run/docker.sock
  
  redis:
    image: redis:7 
    container_name: borealis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
  pgdata: