# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"\"\n\x0fValidateRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"F\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nrate_limit\x18\x03 \x01(\x05\x32=\n\x04\x41uth\x12\x35\n\x0eValidateAPIKey\x12\x10.ValidateRequest\x1a\x11.ValidateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEREQUEST']._serialized_start=14
  _globals['_VALIDATEREQUEST']._serialized_end=48
  _globals['_VALIDATERESPONSE']._serialized_start=50
  _globals['_VALIDATERESPONSE']._serialized_end=120
  _globals['_AUTH']._serialized_start=122
  _globals['_AUTH']._serialized_end=183
# @@protoc_insertion_point(module_scope)
