# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'runner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crunner.proto\"j\n\x10\x45xecutionRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0bsource_code\x18\x03 \x01(\t\x12\r\n\x05stdin\x18\x04 \x01(\t\x12\x0f\n\x07\x65xec_id\x18\x05 \x01(\t\"W\n\x11\x45xecutionResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\x12\x11\n\texit_code\x18\x03 \x01(\x05\x12\x0f\n\x07\x65xec_id\x18\x04 \x01(\t2:\n\x06Runner\x12\x30\n\x07\x45xecute\x12\x11.ExecutionRequest\x1a\x12.ExecutionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTIONREQUEST']._serialized_start=16
  _globals['_EXECUTIONREQUEST']._serialized_end=122
  _globals['_EXECUTIONRESPONSE']._serialized_start=124
  _globals['_EXECUTIONRESPONSE']._serialized_end=211
  _globals['_RUNNER']._serialized_start=213
  _globals['_RUNNER']._serialized_end=271
# @@protoc_insertion_point(module_scope)
