services:

  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    image: api-borealis:latest
    container_name: borealis-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - runner

  runner:
    build: 
      context: .
      dockerfile: docker/execution/Dockerfile
    image: runner-borealis:latest
    container_name: borealis-runner
    ports:
      - "50051:50051"
    env_file:
      - .env
    volumes:
      - /tmp/borealis_jobs:/tmp/borealis_jobs
      - /var/run/docker.sock:/var/run/docker.sock
  
  exec-c_cpp:
    build: 
      context: .
      dockerfile: docker/languages/Dockerfile.c_cpp
    image: borealis-exec-c_cpp:latest

  exec-python:
    build: 
      context: .
      dockerfile: docker/languages/Dockerfile.py
    image: borealis-exec-py:latest

  exec-js:
    build: 
      context: .
      dockerfile: docker/languages/Dockerfile.js
    image: borealis-exec-js:latest


  redis:
    container_name: borealis-redis
    image: redis:7 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}