"""init

Revision ID: ffdfaa94145d
Revises: 
Create Date: 2026-04-18 21:50:30.856835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdfaa94145d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('creation_time', sa.String(), nullable=True),
    )

    op.create_index(
        op.f('ix_user_api_key'),
        'user',
        ['api_key'],
        unique=True
    )

    op.create_table(
        'history',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('exec_id', sa.String(), nullable=True),
        sa.Column('language', sa.String(), nullable=True),
        sa.Column('testcase', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('creation_time', sa.String(), nullable=True),
        sa.Column('execution_time', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['api_key'], ['user.api_key']),
        sa.UniqueConstraint('exec_id'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_index(op.f('ix_user_api_key'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
